### ISSUE TITLE
Cart Story 

### ISSUE THREAD

**Issue by lyleaigbedion** [wdf-2004-grace-shopper-team-h/grace-shopper#14]
As a user, I want to be able to add items into my cart to keep track of the items I want.

- [x] Brainstorm, design, and create a Cart Model that can serve both guests and users #15 
- [x] Create Cart Component #16 
- [x] Create Cart Redux Sub-Reducer #17 
- [ ] Create Cart api Routes #18
