### ISSUE TITLE
Edit My Cart if I Change My Mind

### ISSUE THREAD

**Issue by lyleaigbedion** [wdf-2004-grace-shopper-team-h/grace-shopper#25]
As a user I'd like to change the quantity of a product in my cart, remove a product in my cart, and no one should be able to make these decisions besides me.

- [x] Make a route that can delete items in a user's cart if they choose to #41 
- [x] Make a put route that can update the quantity of an item in a user's cart #42 
- [x] Create an thunk creator that can log changes from the frontend to send to the route that updates quantity when a user updates the quantity. #43 
- [x] Create a thunk creator that can dispatch a request to delete/remove a specified item from the Cart model that belongs to the user. #44 
- [x] modify the Cart Component to allow the quantity to be changed by the user. #45 
- [x] Ensure the unique cart cannot be edited by any other user  who may be logged in #46
