### ISSUE TITLE
Administrator Rights/Privileges 

### ISSUE THREAD

**Issue by lyleaigbedion** [wdf-2004-grace-shopper-team-h/grace-shopper#36]
As an Administrator, I want to view a single product and have the option to edit or remove it from the database.

- [x] Create an Administrator route that will get a single Product.

- [x] Create an Admin route that can delete a product from the database

- [x] Create an Admin route that can edit a product in the database (inventory, name, description, price).

- [x] Implement an edit button only visible to Administrator accounts when the Admin views a single product. #38 

- [x] Create an Edit Product React Form Component that includes Name, Inventory amount, Description, and price fields.  #39

- [x] Include a remove Product from Database option in the list view of All Products and on single Product view for Admins Only. #40
