### ISSUE TITLE
All Products Story 

### ISSUE THREAD

**Issue by lyleaigbedion** [wdf-2004-grace-shopper-team-h/grace-shopper#8]
As a user, I want to immediately see what this site has to offer in terms of products so I can minimize the search for the type item i am looking for on the internet.

- [x] create component for all products #9 
- [x] create model for All Products #10 
- [x] create seed file of Board Games and Card games for Product Model #11 
- [x] create route to fetch all products #12 
- [x] create redux sub-reducer for all products #13
